### ISSUE TITLE
[USER-STORY] Create UI Elements to assign importance to decisions

### ISSUE THREAD

**Issue by Garret-Gallant** [MetroCS/cs3250_practice#51]
# User Story

## Story
As a user I want to assign a level of importance to each factor of a given choice so that I can rank choices based on what I care most about.

### Rules
* UI must accommodate the assignment of importance 

## Supporting Information
Written by Garret Gallant, Santos Adducci

**Comment by jody** [comment]
A great start!
This seems like it is probably an "epic".

Some modifications are needed to move this forward. 

Please modify the Title to reflect the user's want, rather than the developer's task.

The acceptance criterion is not specific enough to verify that the product satisfies this user story. For example, the lack of a mention of "factor" suggests that this user story may depend on the completion of other user stories that don't yet exist.

**Comment by jody** [comment]
Please have your collaborator add a comment to this issue so that they can be added as an assignee.

**Comment by jody** [comment]
Please update the stakeholder type from "user" to "decision-maker" to match the stakeholder types found in the [web documentation](https://metrocs.github.io/cs3250_practice/) and the [decision_support/README.md](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/README.md)

**Comment by jody** [comment]
Here's a reaction from a Decision-Maker: _The phrase "assign a level of importance to each factor of a given choice" is confusing. I'm not clear on what this means. Different factors have different levels of importance and the relative importance is the same across the alternatives. It seems like the phrase would be clearer if it left out the words "of a given choice"._

The suggested modification to this user story makes it clearer.  I think it has the same meaning as "assign a level of importance to each factor involved in making a given decision".

 There's a separate user story to be written that addresses assigning relative values to alternatives within a given factor.

**Comment by Nitnop** [comment]
Garret, can you tell me more about the UI you want, and does #56 work for you

**Comment by jody** [comment]
Am considering closing this issue due to lack of response and potential confusion about the status of items still marked "triage".

**Comment by Garret-Gallant** [comment]
I would love to reopen this issue since arriving back to class, apologies I was not present the past few days as stated I was on vacation; had much less internet than anticipated considering the circumstances. 

Thanks!
