### ISSUE TITLE
[REQUEST] Decision Chain

### ISSUE THREAD

**Issue by JamiBean** [MetroCS/cs3250_practice#57]
# User Story: Decision Chain

## Story
As a decision maker <br>
I want to be able to have a chain of event_ <br>
so that my past decisions will help with my future decisions.

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* _[Rule 1] : passed decision will be logged
* _[Rule 2]_past decisions will be rated on impact score
* _[Rule 3]_provided decisions it will recommend 

### Scenario 1
**Given**   passed input decisions  
**when**  a new decision is input
**then** prior decisions will help way in the new decisions 

## Supporting Information
_[Relevant information, context, resources, references]_

### Depends On   
_[Links to other issues on which this story depends]_  
### Dependents  
_[Links to other issues that depend on this story]_

**Comment by jody** [comment]
There appears to be good information here that needs to be clarified so the reader knows what to do.

The phrase "chain of event" is new to this project, so it needs to be explained.

The acceptance criteria need to explain a way to _determine_ if the product meets the user story. Some appear to be suggestions for specific solutions; others are not clear how they are intended to be used.

**Comment by jody** [comment]
Please have your collaborator add a comment to this issue so that they can be recognized and added as an assignee.

**Comment by jody** [comment]
Please update the stakeholder type from "end user" to "decision-maker" to match the stakeholder types found in the [web documentation](https://metrocs.github.io/cs3250_practice/) and the [decision_support/README.md](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/README.md)

**Comment by apluskett** [comment]
> The phrase "chain of event" is new to this project, so it needs to be explained.
> 
the "Chain of events" would be using prior inputs to help guide new inputs. Ex you had 3 choices in the past and you go to make a new decision. The prior chains would then be populated and help guide the new decision by helping weigh the old inputs and the new inputs for the next future decision.

**Comment by zAtkinsonSchool** [comment]
I helped with making the user story before it was put into the issues page.

**Comment by JamiBean** [comment]
decision chain is supposed to be that is tracking and reading your decisions.  it is the technique and guidance that aids in the concept of decisions making and allows it to influence the response that the app gives. This will enable the app to figure out the factors used and better direct towards the options. This is on a basis of labels and directions. And gives us worth because it aids in my directional compatibilities. Such as if I was to input previous data I would want to play with possible outcomes with the intent to find a solution.

**Comment by jody** [comment]
A very interesting enhancement that deserves further attention. Will mark this as a [REQUEST] and something to be addressed in the future.

**Comment by jody** [comment]
Based on offline discussions, this is an idea for a future feature. I've created a discussion for this topic #91 and will close this issue pending the outcome of that discussion.
