### ISSUE TITLE
[USER-STORY]: Decision-Maker - Relative Importance of Factors

### ISSUE THREAD

**Issue by tonysan98** [MetroCS/cs3250_practice#58]
# User Story

## Story
[User-Story]

As a decision-maker I want to assign importance weight levels to the factors that are more significant to me

so that:

the output I receive is consistent with my priorities

### Rules
* _Each factor is assigned a level of relative importance determined by the decision-maker.._

## Supporting Information

[User story resource link](https://www.easyagile.com/blog/how-to-write-good-user-stories-in-agile-software-development/)

### Depends On   
* _UI Text Fields for each factor_  
* _UI button to submit_
### Dependents  
* _UI (frontend)_  
* _backend algorithms_

**Comment by jody** [comment]
This is a good start for a user story!

Perhaps the user story's "I want" part should be what is given in the "so that" part. For example,
_As a user, I want the product to give more importance to the factors are more significant to me, so that..._

Now we need to know why the user wants this.

**Comment by jody** [comment]
Please have your collaborator add a comment to this issue so that they can be added as an assignee.

**Comment by jody** [comment]
Please update the stakeholder type from "user" to "decision-maker" to match the stakeholder types found in the [web documentation](https://metrocs.github.io/cs3250_practice/) and the [decision_support/README.md](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/README.md)

**Comment by Donsch377** [comment]
Commented

**Comment by jody** [comment]
The story looks great... but it might be too big to satisfy all at once.

Another way to check that is by ensuring the acceptance criteria match the intent without over-prescribing how that is accomplished.

>Rules
>Each factor has a significance level entered by the user
>
>Scenario 1
>Given two factors
>when I give one factor a weight of 100 and another a different weight of 50
>then the factor with the weight of a 100 will be twice as important as the other factor

Both the rule and the Scenario presume particular implementations.

The rule presumes that _the user enters a significance level_ for each factor, which might not be the only way that the significance levels are established. For example, the user might be entering pairwise values and the product might use those to derive the significance levels for each factor.

The scenario presumes that the user enters numeric values, which might not be necessary. For example, the user might position a slider between two factors using the visual distance as the indicator of relative importance. The product might use those to derive numerical values.

**Comment by jody** [comment]
Let's drop the scenario and stick to just rules.  Here's the original:

> Each factor has a significance level entered by the user

The [documentation](https://metrocs.github.io/cs3250_practice/ProductOverview.html) states
"Each factor can have a different level of relative importance."

How about using that terminology in the rule? For example,  
"Each factor has a level of relative importance determined by the decision-maker."

This wording, "determined by", is more general and allows for actual values to be derived from information entered by the decision-maker.

**Comment by tonysan98** [comment]
Edited user story to implement the changes recommended.

**Comment by tonysan98** [comment]
User story ready for review

**Comment by jody** [comment]
Acceptance Criteria: How will the decision-maker determine whether or not the product supported them to "assign importance weight levels to the factors that are more significant to me"?  This is what we mean by acceptance criteria.

Given the specifications of how decision-makers interact with the product, this would involve the two-item comparison process and ensuring that all factors have been involved in the comparisons.  See: [Decision Support Process](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/DSSProcess.md)

"Dependencies" refers to existing issues, each linked using # followed by their number. If appropriate, please create an issue for each of the items on which this depends, then add those as links in the "Depends On" section.

**Comment by jody** [comment]
Marked this as depending on user-story #116 which addresses the two-at-a-time method for eliciting this information from decision-makers.

**Comment by jody** [comment]
Is there now more to this than #116 ?  Or are they now duplicates that can be merged?

**Comment by jody** [comment]
Assuming lack of response means this is a duplicate. Closing accordingly.
