### ISSUE TITLE
Categories for Decision Type User Story

### ISSUE THREAD

**Issue by Sporgl** [MetroCS/cs3250_practice#59]
# User Story

## Story
As an decision-maker <br>
I want to have categories available <br>
so that I can choose what kind of decision aid I want

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* Be able to select what kind of decision aid I want.
* The process to only require a couple clicks
* Choosing a category automatically inputs required information for a certain type of decision aid 

### Scenario 1
**Given**  The user wants a specific kind of decision aid
**when**  The user selects a category
**then**   Required information for that category is automatically input

## Supporting Information
Sean Berna (Sporgl)

**Comment by jody** [comment]
This user story provides a good start!

Here are areas that need to be addressed before it can be moved into **Ready**.

The user story itself is probably too generic to define an effective acceptance criterion. Based on the user story, the acceptance criteria need to show that the product "streamlines" the user's decision-making process. That requires there to be a metric for "streamlining".

Note that the acceptance criteria also need to match the actual user story _without constraining_ the developers in **how** the product satisfies that user story.

The stated acceptance criteria are a collection of _possible_ designs and implementations but are _not the only_ such designs or implementations.

Consider rewriting the user story to have a more measurable objective.

**Comment by jody** [comment]
Please have your collaborator add a comment to this issue so that they can be recognized and added as an assignee.

**Comment by jody** [comment]
Please update the stakeholder type from "end user" to "decision-maker" to match the stakeholder types found in the [web documentation](https://metrocs.github.io/cs3250_practice/) and the [decision_support/README.md](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/README.md)

**Comment by jody** [comment]
This is an interesting idea!

I suggest starting a [discussion](https://github.com/MetroCS/cs3250_practice/discussions) to develop the idea further and get it ready to be written as specific user stories.

**Comment by jody** [comment]
The topic of "Decision Categories" is now a discussion: #88
