### ISSUE TITLE
decision sliders

### ISSUE THREAD

**Issue by Nitnop** [MetroCS/cs3250_practice#74]
# User Story

## Story
As a app user <br>
I want the app to not have enough points to make all the attributes even <br>
So that I have to put points where they are needed most to help with decision making. <br>

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* User needs a points system
* Points system needs to NOT have enough points to fill all the sliders to force the user to make decisions 
* sliders need to be easy to move and 'click' into whole numbers
* Sliders need to display the number they represent in a field to the right of the sliders
* Bonus if the field can be clicked on and a number can be entered if not that will become a different story
* If field clicked keypad needs to automatically come up
* need one slider for each of our 5 decision making metrics
* each slider should be able to accept a value of 0,1,2,3,4,5
* max of 12 points can be assigned to sum of all sliders
* Sliders default to 0 at start of user value process
* Need a field 'points remaining' at the top to show points allowance
* field should be able to go into negative numbers and turn red and pop up a message saying 'use less points to save'
* the user does not need to use all the points to save and exit

### Scenario 1
**Given** user makes a new entry into the app and arrives on this page
**when**  the user sets points into the 5 areas to help the app make decisions
**then**  as long as the users 'point balance' isn't negative they can save and exit and the app will do its magic and organize this 'thing' into their to do list based on the points assigned and filters currently in use

## Supporting Information
this was expected and should not be that hard to implement, we have been watching user reviews in the app store

## Dependencies 
#56   
### Dependents  
_[Links to other issues that depend on this story]_

**Comment by jody** [comment]
This issue needs a stronger connection to an objective of the decision-maker and less constraints on how the developer supports that objective. Where is the support for decision-maker stakeholders having specified that an even number of attributes are required.

**Comment by jody** [comment]
Based on offline discussions, this is identified as anticipatory design thoughts.

Closing the issue as no longer a user-story.
