### ISSUE TITLE
Top Decision Category

### ISSUE THREAD

**Issue by NoorMohamed1885** [MetroCS/cs3250_practice#78]
# User Story

## Story
As a user <br>
I want a display window for categories <br>
so that the categories can have somewhere to be shown

### Scenario 1
**Given**  The user is on the display window  
**when**  The categories are loaded onto the display window  
**then**  The user can view all the inputted categories from the display window 

### Depends On   
#59

**Comment by jody** [comment]
The context of this user story isn't clear. (That may be a by-product of the source epic upon which this is based.) The acceptance criteria also doesn't help clarify how satisfaction of this user story would be measured.

**Comment by jody** [comment]
The topic of "Decision Categories" is now a discussion: #88
