### ISSUE TITLE
[USER-STORY] Creating a decision

### ISSUE THREAD

**Issue by zAtkinsonSchool** [MetroCS/cs3250_practice#79]
# User Story

## Story
As a decision maker <br>
I want define a problem <br>
so that I can work with the problem.

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* must be able to create a decision and add details to it using text

## Supporting Information
Looking at some of the epics, I was trying to figure out how to break them down into smaller pieces, and after working through it a bit, this seemed like a good starting point to build on, as anything related to processing decisions or making a decision (such as creating and choosing between multiple decisions, adding weights to decisions, or having something pick a decision for you) starts with a decision being created.

## Dependencies   
N/A

### Dependents  
#55

**Comment by jody** [comment]
Based on offline discussion, this is a user-interface design issue. I am closing it for now; to be reopened if there is evidence of a requirement from decision-maker stakeholders.
