### ISSUE TITLE
[USER-STORY] Specific Decision Categories 

### ISSUE THREAD

**Issue by jerem-dough** [MetroCS/cs3250_practice#80]
# User Story

## Story
As a contributor <br>
I want a list of decision categories <br>
so that we have a basis for implementing this feature

## Acceptance Criteria
We have a dedicated list of decision categories, as well as the factors that affect each, that can be edited and changed in the future. 

### Rules
* This is a list that can be viewed by all contributors.
* It can be edited and changed as time goes on.
* It includes the major factors that can determine each decision.

### Scenario 1
**Given**  A contributor begins to work on logic for the decision category feature
**When**  They are unsure of what should be included
**Then**  They can refer to the dedicated list 

## Supporting Information
*This is just an initial step to the implementation of this feature. 

### Depends On
None
### Dependents   
#59

**Comment by jody** [comment]
What is a "decision cateogry"? Is there a way to determine if the "list" has appropriate content? 
(Issue #59 indicates that there is a need for additional discussion.)
