### ISSUE TITLE
[USER-STORY] Maintainer - Contributor Info - Code of Conduct

### ISSUE THREAD

**Issue by Angela-Fl** [MetroCS/cs3250_practice#81]
# User Story

## Story
As a Maintainter <br>
I want information about how I am expected to conduct myself <br>
so that I know what others expect of me and what I should expect of them.

### Rules
* The contributor documentation states the community's core values.
* The contributor documentation includes specific examples of behavior that upholds these values.
* The contributor documentation includes specific examples of behavior that does not uphold these values and that is unacceptable.
* The contributor documentation states who will enforce these standards.
* The contributor documentation states the scope of the code of conduct.  
* The contributor documentation states how to report unacceptable behavior.
* The contributor documentation states the consequences of actions that violate the code of conduct. 

## Supporting Information
[Contributor Covenant](https://www.contributor-covenant.org/)
[Redistricting Project Code of Conduct](https://github.com/MetroCS/redistricting/blob/main/CODE_OF_CONDUCT.md)

### Depends On   
_[Links to other issues on which this story depends]_  
### Dependents  
#65 #77

**Comment by jody** [comment]
Thank you for the clarity and (especially) the Supporting Information!
