### ISSUE TITLE
[USER-STORY] - Implement significance level input for factors

### ISSUE THREAD

**Issue by Heiwee-Htoo** [MetroCS/cs3250_practice#82]
# User Story

## Story
As a decision-maker, I want to be able to enter significance levels for each factor, so that the system can prioritize factors based on these levels.

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
The user should be able to enter a numerical significance level for each factor.
The system should allow weights between 1 and 100.

### Scenario 1
**Given** two factors,
- **When** the user assigns a significance level of 100 to one factor and 50 to another,
- **Then** the system will treat the factor with 100 as twice as important as the one with 50.

## Supporting Information
_[Relevant information, context, resources, references]_

### Dependents  
Depends on epic: #60

**Comment by jody** [comment]
User story is clear and appropriate!

The acceptance criteria is a bit too specific without an associated justification. Why is the number 100 required to be the value used in the product? This seems to be a design specification rather than a product requirement.

**Comment by jody** [comment]
Deleting the second rule would make the rules more appropriate.

The scenario is OK, but is just one example and thus not general enough. The idea behind it is great. Please rewrite so that it applies to any pair of significance levels.

**Comment by jody** [comment]
In addition, please move the reference to issue #60 from "Depends On" to "Dependents".

**Comment by jody** [comment]
Issue has become stale.
