### ISSUE TITLE
[USER-STORY] Maintainer - Project Conventions Documentation

### ISSUE THREAD

**Issue by jerem-dough** [MetroCS/cs3250_practice#95]
# User Story

## Story
As a Maintainer <br>
I want documentation to identify project conventions <br>
so that the format of future contributions is clear.

### Rules
* Documentation exists
* Documentation includes but is not limited to:
     * Language conventions
     * Exception/error handling conventions and standard methods
     * Version control and commit message conventions
     * Readme.txt conventions

## Supporting Information
[Codacy Code Documentation](https://blog.codacy.com/code-documentation)

### Depends On   
None 
### Dependents  
#65

**Comment by jody** [comment]
Please add a meaningful title to this issue.

The detail in the acceptance criteria is appreciated.

Potential concerns are
(a) whether these criteria are exhaustive
(b) whether each criterion is necessary
(c) how each of the acceptance criteria are to be measured

With the given level of detail, the implication is that these criteria are exhaustive. No other criteria will be considered.

If any of the criteria are not necessary, developers will still need to meet them.

A lack of clarity in how the product can be checked for compliance with the acceptance criteria results in either the user story never being closable or it being closed without adequate evidence.

**Comment by jerem-dough** [comment]
A. List updated, it no longer implies these rules are exhaustive 
B. Each listed criterion is necessary, but the list is not limited to these 
C. This is an epic, measurements will be more divisive with further, smaller-scope, user stories.

**Comment by jody** [comment]
The dependent issue #65 is now closed.

Please review to see if new issues are needed to address intent not covered by this story.
