### ISSUE TITLE
[USER-STORY] Create Documentation For Coding Standards

### ISSUE THREAD

**Issue by jmaestas7** [MetroCS/cs3250_practice#96]
# User Story

## Story
As a Contributor <be>
I want documentation on the project's coding standards and style guides <be>
so that I can write consistent and maintainable code that aligns with the project's conventions

Acceptance Criteria

### Rules
* The documentation must clearly define the coding standards for the project's primary programming languages (e.g., Python, JavaScript).
* The documentation must include links to external style guides such as PEP 8 (for Python) or ESLint (for JavaScript).
* The documentation must specify any deviations or custom rules that are unique to the project.
* The documentation must include example code snippets for each standard to illustrate how they should be applied.
* The documentation must be accessible from the project's main repository in a dedicated section (e.g., CONTRIBUTING.md or docs folder).

### Scenario 1
Given a contributor is unfamiliar with the project’s coding conventions
when they access the documentation
then they can find detailed information about the required coding standards and style guides and examples to guide their code contributions.

## Supporting Information
[Drupal Coding Standards](https://www.drupal.org/docs/develop/standards)

### Is a Dependent Of
#84
### Dependents  
#97

**Comment by jody** [comment]
Neither of the Dependencies linked are now active issues.

Please review existing documentation and identify improvements via specific issues.
