### ISSUE TITLE
[USER-STORY] efine Python Coding Standards

### ISSUE THREAD

**Issue by jmaestas7** [MetroCS/cs3250_practice#97]
# User Story

## Story
As a Contributor <br>
I want clear documentation of the coding standards and style guides for Python <br>
so that I can follow consistent practices when working with Python code in the project.

### Rules
* The Python coding standards must adhere to PEP 8 as a base guide.
* The documentation must highlight any project-specific conventions or deviations from PEP 8.
* The documentation must include example code snippets demonstrating correct usage of common Python conventions (e.g., naming, imports, docstrings).
* The Python section must include links to PEP 8 and other useful Python resources.

## Supporting Information
[Drupal Coding Standards](https://www.drupal.org/docs/develop/standards)
[PEP8 Guide](https://peps.python.org/pep-0008)

### Is a Dependent Of
#96

**Comment by jody** [comment]
Since the project is using Java, this doesn't seem to be relevant.
