### ISSUE TITLE
[USER-STORY] Create Documentation File

### ISSUE THREAD

**Issue by jmaestas7** [MetroCS/cs3250_practice#98]
# User Story

## Story
As a Contributor <be>
I want a dedicated file for the project's coding standards and style guides <be>
so that all contributors can easily reference the rules for each codebase.

## Acceptance Criteria
_Choose either rules or scenarios and ensure they are verifiable from the perspective of the stakeholder_

### Rules
* _[Rule 1]_
* _[Rule 2]_
* _[Rule 3]_

### Scenario 1
**Given** a contributor wants to learn about coding standards
**When** they navigate to the repository
**Then** they can access the CONTRIBUTING.md or documentation file from the root folder.

### Is A Dependent Of
#96

**Comment by jody** [comment]
This appears to be a duplicate.
